<?php
    // Create Public / Global Variables
    // --------------------------------
    if (TS_VCSC_WordPressCheckup('3.8') == "true") {
        $this->TS_VCSC_Installed_Icon_Fonts = array(
            "Font Awesome"                  	    => "Awesome",
            "Brankic 1979 Font"            		 	=> "Brankic",
            "Countricons Font"              		=> "Countricons",
            "Currencies Font"               		=> "Currencies",
            "Elegant Icons Font"            		=> "Elegant",
            "Entypo Font"                   		=> "Entypo",
            "Foundation Font"               		=> "Foundation",
            "Genericons Font"               		=> "Genericons",
            "IcoMoon Font"                  		=> "IcoMoon",
            "Ionicons Font"                  		=> "Ionicons",
            "MapIcons Font"                		    => "MapIcons",
            "Metrize Font"                		    => "Metrize",
            "Monuments Font"                		=> "Monuments",
            "Social Media Font"             		=> "SocialMedia",
            "Themify Font"                          => "Themify",
            "Typicons Font"                 		=> "Typicons",
            "Dashicons"                             => "Dashicons",
            "Custom User Font"              		=> "Custom",
        );
        $this->TS_VCSC_Icon_Font_Settings = array(
            "Font Awesome"                  	    => array("setting" => "Awesome",                "author" => "Dave Gandy",               "type" => "Standard",       "default" => "true",		"active" => "true",     "always" => "false",        "class" => "ts-awesome-",               "count" => "585"),
            "Brankic 1979 Font"            		 	=> array("setting" => "Brankic",                "author" => "Brankic1979",              "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-brankic-",               "count" => "350"),
            "Countricons Font"              		=> array("setting" => "Countricons",            "author" => "Freepik",                  "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-countricons-",           "count" => "194"),
            "Currencies Font"               		=> array("setting" => "Currencies",             "author" => "Freepik",                  "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-currencies-",            "count" => "89"),
            "Elegant Icons Font"            		=> array("setting" => "Elegant",                "author" => "Elegant Themes",           "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-elegant-",               "count" => "360"),
            "Entypo Font"                   		=> array("setting" => "Entypo",                 "author" => "Entypo",                   "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-entypo-",                "count" => "284"),
            "Foundation Font"               		=> array("setting" => "Foundation",             "author" => "ZURB University",          "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-foundation-",            "count" => "283"),
            "Genericons Font"               		=> array("setting" => "Genericons",             "author" => "Automatic",                "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-genericons-",            "count" => "122"),
            "IcoMoon Font"                  		=> array("setting" => "IcoMoon",                "author" => "Keyamoon",                 "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-icomoon-",               "count" => "451"),
            "Ionicons Font"                  		=> array("setting" => "Ionicons",               "author" => "Ionic Framework",          "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-ionicons-",              "count" => "601"),
            "MapIcons Font"                		    => array("setting" => "MapIcons",               "author" => "Scott De Jonge",           "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-mapicons-",              "count" => "176"),
            "Metrize Font"                		    => array("setting" => "Metrize",                "author" => "Alessio Atzeni",           "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-metrize-",               "count" => "300"),
            "Monuments Font"                		=> array("setting" => "Monuments",              "author" => "Freepik",                  "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-monuments-",             "count" => "255"),
            "Social Media Font"             		=> array("setting" => "SocialMedia",            "author" => "SimpleIcon",               "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-socialmedia-",           "count" => "168"),
            "Themify Font"                 		    => array("setting" => "Themify",                "author" => "Themify",                  "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-themify-",               "count" => "352"),
            "Typicons Font"                 		=> array("setting" => "Typicons",               "author" => "Stephen Hutchings",        "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-typicons-",              "count" => "308"),
            "Dashicons Font"              		    => array("setting" => "Dashicons",              "author" => "WordPress",                "type" => "WordPress",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "dashicons-",                "count" => "201"),
            "Custom User Font"              		=> array("setting" => "Custom",                 "author" => "Custom User Font",         "type" => "Custom",         "default" => "false",		"active" => "false",    "always" => "false",        "class" => "",                          "count" => "0"),
        );
    } else {
        $this->TS_VCSC_Installed_Icon_Fonts = array(
            "Font Awesome"                  	    => "Awesome",
            "Brankic 1979 Font"            		 	=> "Brankic",
            "Countricons Font"              		=> "Countricons",
            "Currencies Font"               		=> "Currencies",
            "Elegant Icons Font"            		=> "Elegant",
            "Entypo Font"                   		=> "Entypo",
            "Foundation Font"               		=> "Foundation",
            "Genericons Font"               		=> "Genericons",
            "IcoMoon Font"                  		=> "IcoMoon",
            "Ionicons Font"                  		=> "Ionicons",
            "MapIcons Font"                		    => "MapIcons",
            "Metrize Font"                		    => "Metrize",
            "Monuments Font"                		=> "Monuments",
            "Social Media Font"             		=> "SocialMedia",
            "Themify Font"                          => "Themify",
            "Typicons Font"                 		=> "Typicons",
            "Custom User Font"              		=> "Custom",
        );
        $this->TS_VCSC_Icon_Font_Settings = array(
            "Font Awesome"                  	    => array("setting" => "Awesome",                "author" => "Dave Gandy",               "type" => "Standard",       "default" => "true",		"active" => "true",     "always" => "false",        "class" => "ts-awesome-",               "count" => "585"),
            "Brankic 1979 Font"            		 	=> array("setting" => "Brankic",                "author" => "Brankic1979",              "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-brankic-",               "count" => "350"),
            "Countricons Font"              		=> array("setting" => "Countricons",            "author" => "Freepik",                  "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-countricons-",           "count" => "194"),
            "Currencies Font"               		=> array("setting" => "Currencies",             "author" => "Freepik",                  "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-currencies-",            "count" => "89"),
            "Elegant Icons Font"            		=> array("setting" => "Elegant",                "author" => "Elegant Themes",           "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-elegant-",               "count" => "360"),
            "Entypo Font"                   		=> array("setting" => "Entypo",                 "author" => "Entypo",                   "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-entypo-",                "count" => "284"),
            "Foundation Font"               		=> array("setting" => "Foundation",             "author" => "ZURB University",          "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-foundation-",            "count" => "283"),
            "Genericons Font"               		=> array("setting" => "Genericons",             "author" => "Automatic",                "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-genericons-",            "count" => "122"),
            "IcoMoon Font"                  		=> array("setting" => "IcoMoon",                "author" => "Keyamoon",                 "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-icomoon-",               "count" => "451"),
            "Ionicons Font"                  		=> array("setting" => "Ionicons",               "author" => "Ionic Framework",          "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-ionicons-",              "count" => "601"),
            "MapIcons Font"                		    => array("setting" => "MapIcons",               "author" => "Scott De Jonge",           "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-mapicons-",              "count" => "176"),
            "Metrize Font"                		    => array("setting" => "Metrize",                "author" => "Alessio Atzeni",           "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-metrize-",               "count" => "300"),
            "Monuments Font"                		=> array("setting" => "Monuments",              "author" => "Freepik",                  "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-monuments-",             "count" => "255"),
            "Social Media Font"             		=> array("setting" => "SocialMedia",            "author" => "SimpleIcon",               "type" => "Specialty",      "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-socialmedia-",           "count" => "168"),
            "Themify Font"                 		    => array("setting" => "Themify",                "author" => "Themify",                  "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-themify-",               "count" => "352"),
            "Typicons Font"                 		=> array("setting" => "Typicons",               "author" => "Stephen Hutchings",        "type" => "Standard",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "ts-typicons-",              "count" => "308"),
            "Custom User Font"              		=> array("setting" => "Custom",                 "author" => "Custom User Font",         "type" => "Custom",         "default" => "false",		"active" => "false",    "always" => "false",        "class" => "",                          "count" => "0"),
        );
    }
    
    $this->TS_VCSC_Composer_Icon_Fonts = array(
        "Font Awesome (VC)"                  	    => "VC_Awesome",
        "Entypo Font (VC)"                          => "VC_Entypo",
        "Linecons Font (VC)"                        => "VC_Linecons",
        "Open Iconic Font (VC)"                     => "VC_OpenIconic",
        "Typicons Font (VC)"                        => "VC_Typicons",
    );
    $this->TS_VCSC_Composer_Font_Settings = array(
        "Font Awesome (VC)"                  	    => array("setting" => "VC_Awesome",             "author" => "Dave Gandy",               "type" => "Composer",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "fa fa-",                    "count" => "536"),
        "Entypo Font (VC)"                          => array("setting" => "VC_Entypo",              "author" => "Entypo",                   "type" => "Composer",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "entypo-icon entypo-",       "count" => "284"),
        "Linecons Font (VC)"                        => array("setting" => "VC_Linecons",            "author" => "Smashing Magazine",        "type" => "Composer",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "vc_li vc_li-",              "count" => "48"),
        "Open Iconic Font (VC)"                     => array("setting" => "VC_OpenIconic",          "author" => "Iconic",                   "type" => "Composer",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "vc-oi vc-oi-",              "count" => "151"),
        "Typicons Font (VC)"                        => array("setting" => "VC_Typicons",            "author" => "Stephen Hutchings",        "type" => "Composer",       "default" => "false",		"active" => "false",    "always" => "false",        "class" => "typcn typcn-",              "count" => "336"),
    );

    $this->TS_VCSC_Visual_Composer_Elements = array(
        "TS Google Charts"						    => array("setting" => "GoogleCharts",           "file" => "google_charts",              "group" => "Google",     	"type" => "internal",		"default" => "false",       "active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Google Tables"						    => array("setting" => "GoogleTables",           "file" => "google_tables",              "group" => "Google",     	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Google Maps PLUS"			            => array("setting" => "GoogleMapsPlus",         "file" => "google_mapsplus",            "group" => "Google",       	"type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "4.6.0",      "lightbox" => "false"),
        "TS Google Maps (Deprecated)"			    => array("setting" => "GoogleMaps",             "file" => "google_maps",                "group" => "Google",       	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",           "lightbox" => "false"),
        "TS Google Docs"						    => array("setting" => "GoogleDocs",             "file" => "google_docs",                "group" => "Google",       	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Google Trends"						    => array("setting" => "GoogleTrends",           "file" => "google_trends",              "group" => "Google",     	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Google Forms"						    => array("setting" => "GoogleForms",            "file" => "google_forms",               "group" => "Google",     	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Icon Fonts"							    => array("setting" => "FontIcons",              "file" => "icon",              			"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",	    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Icon Box"							    => array("setting" => "IconBox",                "file" => "icon_box_tiny",     			"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Icon Box (Deprecated)"				    => array("setting" => "IconBoxOld",             "file" => "icon_box",          			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",           "lightbox" => "false"),
        "TS Icon List Item"						    => array("setting" => "IconList",               "file" => "icon_listitem",     			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Icon 3D Button"						    => array("setting" => "IconButton",             "file" => "icon_button",                "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Icon Flat Button"					    => array("setting" => "IconFlatButton",         "file" => "icon_flatbutton",            "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Icon Dual Button"					    => array("setting" => "IconDualutton",          "file" => "icon_dualbutton",            "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Creative Link"					        => array("setting" => "CreativeLink",           "file" => "creativelink",               "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        //"TS Inspired Button"                      => array("setting" => "InspiredButton",         "file" => "inspiredbutton",             "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Info / Notice"						    => array("setting" => "InfoNotice",             "file" => "info_notice",                "group" => "Popups",        "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Counter Icon"						    => array("setting" => "IconCounter",            "file" => "icon_counter",      			"group" => "Counters",      "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Counter Circle"						    => array("setting" => "CircleCounter",          "file" => "circliful",         			"group" => "Counters",      "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Countdown"							    => array("setting" => "Countdown",              "file" => "countdown",         			"group" => "Counters",      "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Content Flip"						    => array("setting" => "ContentFlip",            "file" => "content_flip",      			"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Meet The Team (Deprecated)"			    => array("setting" => "MeetTeamOld",            "file" => "meet_team",         			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",           "lightbox" => "false"),
        "TS Single Teammate (Deprecated)"		    => array("setting" => "TeammateOld",            "file" => "teammates_old",         		"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",           "lightbox" => "false"),
        "TS Quick Skillset"						    => array("setting" => "QuickSkills",            "file" => "quick_skills",     			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "4.4.0",      "lightbox" => "false"),
        "TS Quick Testimonial"						=> array("setting" => "QuickTestimonial",       "file" => "quick_testimonial",          "group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Pricing Table"						    => array("setting" => "PricingTable",           "file" => "pricing_table",     			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Social Networks"					    => array("setting" => "SocialNetworks",         "file" => "social_networks",   			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Processes"							    => array("setting" => "TimelineOld",            "file" => "timeline",          			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Horizontal Steps"		                => array("setting" => "HorizontalSteps",        "file" => "horizontal_steps",           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Circle Steps"                           => array("setting" => "CircleSteps",            "file" => "circle_steps",               "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Isotope Timeline (Deprecated)"		    => array("setting" => "Timeline",        	    "file" => "timelines",          		"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",           "lightbox" => "true"),
        "TS Posts Isotope Grid"					    => array("setting" => "Postsgrid",        	    "file" => "postsgrid",                  "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),        
        "TS Posts Image Grid"					    => array("setting" => "Postsimage",        	    "file" => "postsimage",                 "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),        
        "TS Posts Slider"					        => array("setting" => "Postsslider",        	"file" => "postsslider",                "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Posts Ticker"					        => array("setting" => "Poststicker",        	"file" => "poststicker",                "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Posts Timeline"					        => array("setting" => "Poststimeline",        	"file" => "poststimeline",              "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Divider"							    => array("setting" => "Divider",                "file" => "divider",           			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Shortcode"							    => array("setting" => "Shortcode",              "file" => "shortcode",         			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Star Rating"						    => array("setting" => "StarRating",             "file" => "seostars",         			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),      
        "TS QR-Code"							    => array("setting" => "QRCode",                 "file" => "qrcode",            			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Teaser Block"						    => array("setting" => "TeaserBlock",            "file" => "teaser_block",      			"group" => "Titles",        "type" => "class",			"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Title Advanced"							=> array("setting" => "IconTitle",              "file" => "icon_title",                 "group" => "Titles",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Title Typed"						    => array("setting" => "TitleTyped",             "file" => "title_typed",                "group" => "Titles",        "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Title Ticker"						    => array("setting" => "TitleTicker",            "file" => "title_ticker",               "group" => "Titles",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Title Textillate"					    => array("setting" => "Textillate",             "file" => "textillate",                 "group" => "Titles",        "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Title Flipboard"					    => array("setting" => "Flipboard",              "file" => "title_flipboard",            "group" => "Titles",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Fancy List"							    => array("setting" => "FancyList",              "file" => "fancylist",            		"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",	    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Image Adipoli"						    => array("setting" => "ImageAdipoli",           "file" => "image_adipoli",              "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Picstrips"					    => array("setting" => "ImagePicstrips",         "file" => "image_picstrips",            "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Caman"						    => array("setting" => "ImageCaman",             "file" => "image_caman",                "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Magnify"						    => array("setting" => "ImageMagnify",           "file" => "image_magnify",              "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Switch"						    => array("setting" => "ImageSwitch",            "file" => "image_switch",               "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Scroll"						    => array("setting" => "ImageScroll",            "file" => "image_scroll",               "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image SVG"						        => array("setting" => "ImageSVG",               "file" => "image_svg",                  "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Full"							    => array("setting" => "ImageFull",        	    "file" => "image_full",                 "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Hotspot"					        => array("setting" => "ImageHotspot",           "file" => "image_hotspot",              "group" => "Media",         "type" => "class",		    "default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "4.3.0",      "lightbox" => "true"),
        "TS Image Basic Overlay"				    => array("setting" => "ImageOverlay",           "file" => "image_overlay",              "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Advanced Overlay"				    => array("setting" => "ImageEffects",           "file" => "image_hovereffects",         "group" => "Media",         "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image iHover"					        => array("setting" => "ImageIHover",            "file" => "image_ihover",               "group" => "Media",         "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),        
        "TS Image Link Grid"					    => array("setting" => "ImageGrid",              "file" => "image_grid",                 "group" => "Media",         "type" => "internal",       "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),        
        "TS Image Lightbox"						    => array("setting" => "LightboxImage",          "file" => "lightbox_image",             "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Image Gallery"					        => array("setting" => "LightboxGallery",        "file" => "lightbox_gallery",           "group" => "Media",         "type" => "class",			"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Lightbox Gallery (Deprecated)"		    => array("setting" => "LightboxGalleryOld",     "file" => "lightbox_gallery_old",       "group" => "Media",  		"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",           "lightbox" => "true"),
        "TS Modal Popup"						    => array("setting" => "ModalPopup",             "file" => "modal",                      "group" => "Popups",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Amaran Popup"						    => array("setting" => "AmaranPopup",            "file" => "amaran",                     "group" => "Popups",        "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS iPresenter"					            => array("setting" => "iPresenter",    		    "file" => "ipresenter",  				"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS SlitSlider"					            => array("setting" => "SlitSlider",    		    "file" => "slitslider",  				"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS IFrame Embed"						    => array("setting" => "IFrame",                 "file" => "iframe",            			"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Soundcloud Player"                      => array("setting" => "Soundcloud",             "file" => "soundcloud",                 "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Mixcloud Player"                        => array("setting" => "Mixcloud",               "file" => "mixcloud",                   "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Audio HTML5"					        => array("setting" => "HTML5Audio",             "file" => "html5audio",                 "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Video HTML5"					        => array("setting" => "HTML5Video",             "file" => "html5video",                 "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Video DailyMotion"					    => array("setting" => "DailyMotion",            "file" => "dailymotion",                "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Video Vimeo"						    => array("setting" => "Vimeo",                  "file" => "vimeo",                      "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS Video YouTube"						    => array("setting" => "YouTube",                "file" => "youtube",                    "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "true"),
        "TS YouTube Background (Deprecated)"        => array("setting" => "Background",             "file" => "background",                 "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",           "lightbox" => "false"),
        "TS Page Background"                        => array("setting" => "PageBackground",         "file" => "page_background",            "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Spacer / Clear"						    => array("setting" => "Spacer",                 "file" => "spacer",            			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        //"TS Login Form"                           => array("setting" => "LoginForm",              "file" => "loginform",                  "group" => "Other",         "type" => "class",		    "default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Almost Anything Slider"					=> array("setting" => "AnySlider",    		    "file" => "anyslider",  				"group" => "Other",         "type" => "class",			"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "TS Animations Frame"					    => array("setting" => "Animations",    		    "file" => "animations",  				"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Element Focus"					        => array("setting" => "ElementFocus",    		"file" => "element_focus",  			"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Figure Navigation"					    => array("setting" => "FigureNavigation",       "file" => "figure_navigation",          "group" => "Buttons",       "type" => "class",			"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Fancy Tabs (BETA)"					    => array("setting" => "FancyTabs",    		    "file" => "fancytabs",                  "group" => "BETA",          "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "4.3.0",      "lightbox" => "false"),        
        "TS Row Center Frame"                       => array("setting" => "RowCenter",    		    "file" => "rowcenter",                  "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "TS Icon Wall"                              => array("setting" => "IconWall",    		    "file" => "iconwall",                   "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        //"TS Sidebar Panel"                        => array("setting" => "Sidebar",    		    "file" => "sidebar",                    "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "GoPricing Table"						    => array("setting" => "GoPricing",              "file" => "gopricing",                  "group" => "Plugins",       "type" => "external",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
        "QuForm"								    => array("setting" => "Quform",                 "file" => "quform",                     "group" => "Plugins",       "type" => "external",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "Real 3D FlipBook"                          => array("setting" => "Real3DFlipbook",         "file" => "real3dflipbook",             "group" => "Plugins",       "type" => "external",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),        
        "Demo Shortcodes"						    => array("setting" => "Demos",             	    "file" => "demos",                      "group" => "Internal",      "type" => "demos",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",           "lightbox" => "false"),
    );
    
    $this->TS_VCSC_ComposerParameters = array(
        "Post Type Paramater"                       => array("file" => "standardpost"),
        "Custom Post Type Parameter"                => array("file" => "custompost"),
        "Load File Parameter"              		    => array("file" => "loadfile"),
        "CSS3 Animation Parameter"                  => array("file" => "animations"),
        "Separator Parameter"            		    => array("file" => "separator"),
        "Messenger Parameter"                       => array("file" => "messenger"),
        "Video Select Parameter"                    => array("file" => "videoselect"),
        "Audio Select Parameter"                    => array("file" => "audioselect"),
        "Icons Panel Parameter"                     => array("file" => "iconspanel"),
        "Background Panel Parameter"                => array("file" => "backgroundpanel"),
        "Map Marker Parameter"                      => array("file" => "markerpanel"),
        "Switch Parameter"                          => array("file" => "switch"),
        "NoUiSlider Parameter"                      => array("file" => "nouislider"),
        "Image Hotspot Parameter"                   => array("file" => "imagehotspot"),
        "Google Fonts Parameter"                    => array("file" => "googlefonts"),
        "Hidden Input Parameter"                    => array("file" => "hiddeninput"),
        "Hidden Textarea Parameter"                 => array("file" => "hiddentextarea"),
        "Date / Time Picker Parameter"              => array("file" => "datetimepicker"),        
        "Advanced Setting Parameter"                => array("file" => "advancedsetting"),
        "Advanced Gradient Parameter"               => array("file" => "advancedgradient"),
        "Social Networks Parameter"                 => array("file" => "socialnetworks"),
        "Device Type Selectors"                     => array("file" => "devicetypes"),
        "ID / Number Auto-Generator"                => array("file" => "autogenerate"),
        //"QuForm Parameter"             		    => array("file" => "quform"),
        //"GoPricing Parameter"                     => array("file" => "gopricing"),
        "WooCommerce Parameters"                    => array("file" => "woocommerce"),
        "bbPress Parameters"              		    => array("file" => "bbpress"),
    );
    
    $this->TS_VCSC_TeamPageBuilder_Included = array (
        // Extensions elements
        'TS_VCSC_Team_Page_Featured',
        'TS_VCSC_Team_Page_NameTitle',
        'TS_VCSC_Team_Page_Contact',
        'TS_VCSC_Team_Page_Social',
        'TS_VCSC_Team_Page_Description',
        'TS_VCSC_Team_Page_Opening',
        'TS_VCSC_Team_Page_Download',
        'TS_VCSC_Team_Page_Skills',
        'TS_VCSC_Star_Rating',
        'TS-VCSC-Icon-Counter',
        'TS-VCSC-Circliful',
        'TS-VCSC-Icon-Title',
        'TS_VCSC_Skill_Sets_Standalone',
        'TS-VCSC-Divider',
        'TS-VCSC-Spacer',
        'TS_VCSC_Spacer',
        'TS-VCSC-QRCode',
        // Original VC Elements
        'vc_column_text',
        'vc_toggle',
        'vc_message',
        'vc_separator',
        'vc_text_separator',
    );
    
    $this->TS_VCSC_AnySlider_Excluded = array (
        // Extension Elements
        'TS_VCSC_Anything_Slider',
        'TS_VCSC_Animation_Frame',
        'TS_VCSC_Timeline_Container',
        'TS_VCSC_Timeline_Single',
        'TS_VCSC_Timeline_Break',
        'TS_VCSC_Team_Mates_Single',
        'TS_VCSC_Team_Mates_Slider_Custom',
        'TS_VCSC_Team_Mates_Slider_Category',
        'TS_VCSC_Testimonial_Single',
        'TS_VCSC_Testimonial_Slider_Custom',
        'TS_VCSC_Testimonial_Slider_Category',
        'TS_VCSC_Teaser_Block_Single',
        'TS_VCSC_Teaser_Block_Slider_Custom',
        'TS_VCSC_Logo_Single',
        'TS_VCSC_Logo_Slider_Custom',
        'TS_VCSC_Logo_Slider_Category',
        'TS_VCSC_Posts_Grid_Standalone',
        'TS_VCSC_Posts_Slider_Standalone',
        'TS-VCSC-Image-Full',
        'TS_VCSC_Image_Full',
        'TS-VCSC-YouTube-Background',
        'TS_VCSC_YouTube_Background',
        'TS-VCSC-Google-Charts',
        'TS_VCSC_Google_Charts',
        'TS-VCSC-Google-Maps',
        'TS_VCSC_Google_Maps',
        'TS-VCSC-Google-Trends',
        'TS_VCSC_Google_Trends',
        'TS-VCSC-Google-Docs',
        'TS_VCSC_Google_Docs',
        'TS-VCSC-Textillate',
        'TS_VCSC_Textillate',
        'TS-VCSC-Icon-Title',
        'TS_VCSC_Icon_Title',
        'TS-VCSC-Timeline',
        'TS_VCSC_Timeline',
        'TS-VCSC-Divider',
        'TS_VCSC_Divider',
        'TS-VCSC-Spacer',
        'TS_VCSC_Spacer',
        // Original VC Elements
        'vc_row',
        'vc_gallery',
        'vc_images_carousel',
        'vc_carousel',
        'vc_posts_slider',
        'vc_accordion',
        'vc_tour',
        'vc_tabs',
        'vc_empty_space',
        'vc_pie',
        // WooCommerce Elements
        'woocommerce_cart',
        'woocommerce_checkout',
        'woocommerce_order_tracking',
        'woocommerce_my_account',
        'add_to_cart',
        'add_to_cart_url',
        'product_page',
        'related_products',
        // Other Elements
        'layerslider',
        'rev_slider',
    );
    
    $this->TS_VCSC_Focus_Excluded = array (
        // Extension Elements
        'TS_VCSC_Element_Focus',
        // Original VC Elements
        'vc_row',
        'vc_accordion',
        'vc_tour',
        'vc_tabs',
        // WooCommerce Elements
        'woocommerce_cart',
        'woocommerce_checkout',
        'woocommerce_order_tracking',
        'woocommerce_my_account',
        'add_to_cart',
        'add_to_cart_url',
        'product_page',
        'related_products',
        // Other Elements
        'layerslider',
        'rev_slider',
    );
    
    $this->TS_VCSC_WooCommerce_Elements = array(
        "Recent Products"						=> array("setting" => "RecentProducts",		    "file" => "recent",             		"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Featured Products"						=> array("setting" => "FeaturedProducts",	    "file" => "featured",             		"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Products on Sale"						=> array("setting" => "SaleProducts",		    "file" => "saleproducts",				"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Top Rated Products"					=> array("setting" => "TopRatedProducts",	    "file" => "toprated",             		"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Top Selling Products"					=> array("setting" => "TopSellingProducts",	    "file" => "topselling",             	"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Related Products"						=> array("setting" => "RelatedProducts",	    "file" => "related",             		"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Single Product Preview"				=> array("setting" => "SingleProduct",		    "file" => "singleproduct",             	"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Single Product Page"					=> array("setting" => "SingleProductPage",	    "file" => "singleproductpage",			"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Multiple Products"						=> array("setting" => "MultipleProducts",	    "file" => "multipleproducts",			"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Add To Cart Button"					=> array("setting" => "AddToCartButton",	    "file" => "addtocartbutton",			"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Add To Cart URL"						=> array("setting" => "AddToCartURL",		    "file" => "addtocarturl",				"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Products by Attribute"					=> array("setting" => "AttributeProducts",	    "file" => "attributes",             	"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Products in Single Category"			=> array("setting" => "SingleCategory",		    "file" => "singlecategory",				"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Product Categories"					=> array("setting" => "MultipleCategories",	    "file" => "multiplecategories",			"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Page - Cart"							=> array("setting" => "ShowCart",			    "file" => "showcart",					"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Page - Checkout"						=> array("setting" => "ShowCheckout",		    "file" => "showcheckout",				"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Page - My Account"						=> array("setting" => "ShowAccount",		    "file" => "showaccount",				"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Page - Order Tracking"					=> array("setting" => "OrderTracking",		    "file" => "tracking",             		"type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Basic Products Slider"				    => array("setting" => "SliderBasic",		    "file" => "custom_slider",             	"type" => "class",	        "default" => "false",		"active" => "false",	"deprecated" => "false",        "lightbox" => "true"),
        "Basic Products Isotope Grid"           => array("setting" => "GridBasic",		        "file" => "custom_grid",             	"type" => "class",	        "default" => "false",		"active" => "false",	"deprecated" => "false",        "lightbox" => "true"),
        "Basic Products Image Grid"             => array("setting" => "GridImage",		        "file" => "custom_image",             	"type" => "class",	        "default" => "false",		"active" => "false",	"deprecated" => "false",        "lightbox" => "true"),
        "Basic Products Ticker"				    => array("setting" => "TickerBasic",		    "file" => "custom_ticker",             	"type" => "class",	        "default" => "false",		"active" => "false",	"deprecated" => "false",        "lightbox" => "false"),
        "Single Product Rating"				    => array("setting" => "RatingBasic",		    "file" => "custom_rating",             	"type" => "class",	        "default" => "false",		"active" => "false",	"deprecated" => "false",        "lightbox" => "false"),
    );
    
    $this->TS_VCSC_bbPress_Elements = array(
        "Forum Index"						    => array("setting" => "ForumIndex",		        "file" => "forumindex",                 "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Forum Form"						    => array("setting" => "ForumForm",		        "file" => "forumform",                  "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Single Forums Topics"                  => array("setting" => "ForumSingle",            "file" => "forumsingle",                "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Topic Index"						    => array("setting" => "TopicIndex",		        "file" => "topicindex",                 "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Topic Form"						    => array("setting" => "TopicForm",		        "file" => "topicform",                  "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Single Topic"						    => array("setting" => "TopicSingle",            "file" => "topicsingle",                "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Reply Form"						    => array("setting" => "ReplyForm",		        "file" => "replyform",                  "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Single Reply"						    => array("setting" => "ReplySingle",            "file" => "replysingle",                "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Topic Tags"						    => array("setting" => "TagsTopic",              "file" => "tagstopic",                  "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Single Tags"						    => array("setting" => "TagsSingle",             "file" => "tagssingle",                 "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Single View"						    => array("setting" => "ViewSingle",             "file" => "viewsingle",                 "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Search Form"						    => array("setting" => "SearchForm",             "file" => "searchform",                 "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Search Template"                       => array("setting" => "SearchTemplate",         "file" => "searchtemplate",             "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Login Screen"                          => array("setting" => "AccountLogin",           "file" => "accountlogin",               "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Register Screen"                       => array("setting" => "AccountRegister",        "file" => "accountregister",            "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Lost Password Screen"                  => array("setting" => "AccountPassword",        "file" => "accountpassword",            "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
        "Forum Statistics"                      => array("setting" => "ForumStatistics",        "file" => "forumstatistics",            "type" => "internal",	    "default" => "true",		"active" => "true",		"deprecated" => "false",        "lightbox" => "false"),
    );
?>