<?php
    $this->TS_VCSC_Fonts_Google = array(
        "ABeeZee" => array ("google" => "ABeeZee", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Abel" => array ("google" => "Abel", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Abril Fatface" => array ("google" => "Abril+Fatface", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Aclonica" => array ("google" => "Aclonica", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Acme" => array ("google" => "Acme", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Actor" => array ("google" => "Actor", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Adamina" => array ("google" => "Adamina", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Advent Pro" => array ("google" => "Advent+Pro", "variants" => "100,200,300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Aguafina Script" => array ("google" => "Aguafina+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Akronim" => array ("google" => "Akronim", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Aladin" => array ("google" => "Aladin", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Aldrich" => array ("google" => "Aldrich", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Alef" => array ("google" => "Alef", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Alegreya" => array ("google" => "Alegreya", "variants" => "regular,italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Alegreya SC" => array ("google" => "Alegreya+SC", "variants" => "regular,italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Alegreya Sans" => array ("google" => "Alegreya+Sans", "variants" => "100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,800,800italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Alegreya Sans SC" => array ("google" => "Alegreya+Sans+SC", "variants" => "100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,800,800italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Alex Brush" => array ("google" => "Alex+Brush", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Alfa Slab One" => array ("google" => "Alfa+Slab+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Alice" => array ("google" => "Alice", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Alike" => array ("google" => "Alike", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Alike Angular" => array ("google" => "Alike+Angular", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Allan" => array ("google" => "Allan", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Allerta" => array ("google" => "Allerta", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Allerta Stencil" => array ("google" => "Allerta+Stencil", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Allura" => array ("google" => "Allura", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Almendra" => array ("google" => "Almendra", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Almendra Display" => array ("google" => "Almendra+Display", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Almendra SC" => array ("google" => "Almendra+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Amarante" => array ("google" => "Amarante", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Amaranth" => array ("google" => "Amaranth", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Amatic SC" => array ("google" => "Amatic+SC", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Amethysta" => array ("google" => "Amethysta", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Amiri" => array ("google" => "Amiri", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Anaheim" => array ("google" => "Anaheim", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Andada" => array ("google" => "Andada", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Andika" => array ("google" => "Andika", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Angkor" => array ("google" => "Angkor", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Annie Use Your Telescope" => array ("google" => "Annie+Use+Your+Telescope", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Anonymous Pro" => array ("google" => "Anonymous+Pro", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Antic" => array ("google" => "Antic", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Antic Didone" => array ("google" => "Antic+Didone", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Antic Slab" => array ("google" => "Antic+Slab", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Anton" => array ("google" => "Anton", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Arapey" => array ("google" => "Arapey", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Arbutus" => array ("google" => "Arbutus", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Arbutus Slab" => array ("google" => "Arbutus+Slab", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Architects Daughter" => array ("google" => "Architects+Daughter", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Archivo Black" => array ("google" => "Archivo+Black", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Archivo Narrow" => array ("google" => "Archivo+Narrow", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Arimo" => array ("google" => "Arimo", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Arizonia" => array ("google" => "Arizonia", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Armata" => array ("google" => "Armata", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Artifika" => array ("google" => "Artifika", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Arvo" => array ("google" => "Arvo", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Asap" => array ("google" => "Asap", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Asset" => array ("google" => "Asset", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Astloch" => array ("google" => "Astloch", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Asul" => array ("google" => "Asul", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Atomic Age" => array ("google" => "Atomic+Age", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Aubrey" => array ("google" => "Aubrey", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Audiowide" => array ("google" => "Audiowide", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Autour One" => array ("google" => "Autour+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Average" => array ("google" => "Average", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Average Sans" => array ("google" => "Average+Sans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Averia Gruesa Libre" => array ("google" => "Averia+Gruesa+Libre", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Averia Libre" => array ("google" => "Averia+Libre", "variants" => "300,300italic,regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Averia Sans Libre" => array ("google" => "Averia+Sans+Libre", "variants" => "300,300italic,regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Averia Serif Libre" => array ("google" => "Averia+Serif+Libre", "variants" => "300,300italic,regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Bad Script" => array ("google" => "Bad+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Balthazar" => array ("google" => "Balthazar", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bangers" => array ("google" => "Bangers", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Basic" => array ("google" => "Basic", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Battambang" => array ("google" => "Battambang", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Baumans" => array ("google" => "Baumans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bayon" => array ("google" => "Bayon", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Belgrano" => array ("google" => "Belgrano", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Belleza" => array ("google" => "Belleza", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "BenchNine" => array ("google" => "BenchNine", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Bentham" => array ("google" => "Bentham", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Berkshire Swash" => array ("google" => "Berkshire+Swash", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bevan" => array ("google" => "Bevan", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bigelow Rules" => array ("google" => "Bigelow+Rules", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bigshot One" => array ("google" => "Bigshot+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bilbo" => array ("google" => "Bilbo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bilbo Swash Caps" => array ("google" => "Bilbo+Swash+Caps", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Biryani" => array ("google" => "Biryani", "variants" => "200,300,regular,600,700,800,900", "active" => "false", "favorite" => "false"),
        "Bitter" => array ("google" => "Bitter", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Black Ops One" => array ("google" => "Black+Ops+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bokor" => array ("google" => "Bokor", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bonbon" => array ("google" => "Bonbon", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Boogaloo" => array ("google" => "Boogaloo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bowlby One" => array ("google" => "Bowlby+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bowlby One SC" => array ("google" => "Bowlby+One+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Brawler" => array ("google" => "Brawler", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bree Serif" => array ("google" => "Bree+Serif", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bubblegum Sans" => array ("google" => "Bubblegum+Sans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Bubbler One" => array ("google" => "Bubbler+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Buda" => array ("google" => "Buda", "variants" => "300", "active" => "false", "favorite" => "false"),
        "Buenard" => array ("google" => "Buenard", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Butcherman" => array ("google" => "Butcherman", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Butterfly Kids" => array ("google" => "Butterfly+Kids", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cabin" => array ("google" => "Cabin", "variants" => "regular,italic,500,500italic,600,600italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Cabin Condensed" => array ("google" => "Cabin+Condensed", "variants" => "regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Cabin Sketch" => array ("google" => "Cabin+Sketch", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Caesar Dressing" => array ("google" => "Caesar+Dressing", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cagliostro" => array ("google" => "Cagliostro", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Calligraffitti" => array ("google" => "Calligraffitti", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cambay" => array ("google" => "Cambay", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Cambo" => array ("google" => "Cambo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Candal" => array ("google" => "Candal", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cantarell" => array ("google" => "Cantarell", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Cantata One" => array ("google" => "Cantata+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cantora One" => array ("google" => "Cantora+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Capriola" => array ("google" => "Capriola", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cardo" => array ("google" => "Cardo", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Carme" => array ("google" => "Carme", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Carrois Gothic" => array ("google" => "Carrois+Gothic", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Carrois Gothic SC" => array ("google" => "Carrois+Gothic+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Carter One" => array ("google" => "Carter+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Caudex" => array ("google" => "Caudex", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Cedarville Cursive" => array ("google" => "Cedarville+Cursive", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ceviche One" => array ("google" => "Ceviche+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Changa One" => array ("google" => "Changa+One", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Chango" => array ("google" => "Chango", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Chau Philomene One" => array ("google" => "Chau+Philomene+One", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Chela One" => array ("google" => "Chela+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Chelsea Market" => array ("google" => "Chelsea+Market", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Chenla" => array ("google" => "Chenla", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cherry Cream Soda" => array ("google" => "Cherry+Cream+Soda", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cherry Swash" => array ("google" => "Cherry+Swash", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Chewy" => array ("google" => "Chewy", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Chicle" => array ("google" => "Chicle", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Chivo" => array ("google" => "Chivo", "variants" => "regular,italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Cinzel" => array ("google" => "Cinzel", "variants" => "regular,700,900", "active" => "false", "favorite" => "false"),
        "Cinzel Decorative" => array ("google" => "Cinzel+Decorative", "variants" => "regular,700,900", "active" => "false", "favorite" => "false"),
        "Clicker Script" => array ("google" => "Clicker+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Coda" => array ("google" => "Coda", "variants" => "regular,800", "active" => "false", "favorite" => "false"),
        "Coda Caption" => array ("google" => "Coda+Caption", "variants" => "800", "active" => "false", "favorite" => "false"),
        "Codystar" => array ("google" => "Codystar", "variants" => "300,regular", "active" => "false", "favorite" => "false"),
        "Combo" => array ("google" => "Combo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Comfortaa" => array ("google" => "Comfortaa", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Coming Soon" => array ("google" => "Coming+Soon", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Concert One" => array ("google" => "Concert+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Condiment" => array ("google" => "Condiment", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Content" => array ("google" => "Content", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Contrail One" => array ("google" => "Contrail+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Convergence" => array ("google" => "Convergence", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cookie" => array ("google" => "Cookie", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Copse" => array ("google" => "Copse", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Corben" => array ("google" => "Corben", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Courgette" => array ("google" => "Courgette", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cousine" => array ("google" => "Cousine", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Coustard" => array ("google" => "Coustard", "variants" => "regular,900", "active" => "false", "favorite" => "false"),
        "Covered By Your Grace" => array ("google" => "Covered+By+Your+Grace", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Crafty Girls" => array ("google" => "Crafty+Girls", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Creepster" => array ("google" => "Creepster", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Crete Round" => array ("google" => "Crete+Round", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Crimson Text" => array ("google" => "Crimson+Text", "variants" => "regular,italic,600,600italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Croissant One" => array ("google" => "Croissant+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Crushed" => array ("google" => "Crushed", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cuprum" => array ("google" => "Cuprum", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Cutive" => array ("google" => "Cutive", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Cutive Mono" => array ("google" => "Cutive+Mono", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Damion" => array ("google" => "Damion", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Dancing Script" => array ("google" => "Dancing+Script", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Dangrek" => array ("google" => "Dangrek", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Dawning of a New Day" => array ("google" => "Dawning+of+a+New+Day", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Days One" => array ("google" => "Days+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Dekko" => array ("google" => "Dekko", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Delius" => array ("google" => "Delius", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Delius Swash Caps" => array ("google" => "Delius+Swash+Caps", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Delius Unicase" => array ("google" => "Delius+Unicase", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Della Respira" => array ("google" => "Della+Respira", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Denk One" => array ("google" => "Denk+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Devonshire" => array ("google" => "Devonshire", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Dhurjati" => array ("google" => "Dhurjati", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Didact Gothic" => array ("google" => "Didact+Gothic", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Diplomata" => array ("google" => "Diplomata", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Diplomata SC" => array ("google" => "Diplomata+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Domine" => array ("google" => "Domine", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Donegal One" => array ("google" => "Donegal+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Doppio One" => array ("google" => "Doppio+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Dorsa" => array ("google" => "Dorsa", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Dosis" => array ("google" => "Dosis", "variants" => "200,300,regular,500,600,700,800", "active" => "false", "favorite" => "false"),
        "Dr Sugiyama" => array ("google" => "Dr+Sugiyama", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Droid Sans" => array ("google" => "Droid+Sans", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Droid Sans Mono" => array ("google" => "Droid+Sans+Mono", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Droid Serif" => array ("google" => "Droid+Serif", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Duru Sans" => array ("google" => "Duru+Sans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Dynalight" => array ("google" => "Dynalight", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "EB Garamond" => array ("google" => "EB+Garamond", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Eagle Lake" => array ("google" => "Eagle+Lake", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Eater" => array ("google" => "Eater", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Economica" => array ("google" => "Economica", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Ek Mukta" => array ("google" => "Ek+Mukta", "variants" => "200,300,regular,500,600,700,800", "active" => "false", "favorite" => "false"),
        "Electrolize" => array ("google" => "Electrolize", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Elsie" => array ("google" => "Elsie", "variants" => "regular,900", "active" => "false", "favorite" => "false"),
        "Elsie Swash Caps" => array ("google" => "Elsie+Swash+Caps", "variants" => "regular,900", "active" => "false", "favorite" => "false"),
        "Emblema One" => array ("google" => "Emblema+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Emilys Candy" => array ("google" => "Emilys+Candy", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Engagement" => array ("google" => "Engagement", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Englebert" => array ("google" => "Englebert", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Enriqueta" => array ("google" => "Enriqueta", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Erica One" => array ("google" => "Erica+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Esteban" => array ("google" => "Esteban", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Euphoria Script" => array ("google" => "Euphoria+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ewert" => array ("google" => "Ewert", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Exo" => array ("google" => "Exo", "variants" => "100,100italic,200,200italic,300,300italic,regular,italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Exo 2" => array ("google" => "Exo+2", "variants" => "100,100italic,200,200italic,300,300italic,regular,italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Expletus Sans" => array ("google" => "Expletus+Sans", "variants" => "regular,italic,500,500italic,600,600italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Fanwood Text" => array ("google" => "Fanwood+Text", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Fascinate" => array ("google" => "Fascinate", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fascinate Inline" => array ("google" => "Fascinate+Inline", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Faster One" => array ("google" => "Faster+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fasthand" => array ("google" => "Fasthand", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fauna One" => array ("google" => "Fauna+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Federant" => array ("google" => "Federant", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Federo" => array ("google" => "Federo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Felipa" => array ("google" => "Felipa", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fenix" => array ("google" => "Fenix", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Finger Paint" => array ("google" => "Finger+Paint", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fira Mono" => array ("google" => "Fira+Mono", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Fira Sans" => array ("google" => "Fira+Sans", "variants" => "300,300italic,regular,italic,500,500italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Fjalla One" => array ("google" => "Fjalla+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fjord One" => array ("google" => "Fjord+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Flamenco" => array ("google" => "Flamenco", "variants" => "300,regular", "active" => "false", "favorite" => "false"),
        "Flavors" => array ("google" => "Flavors", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fondamento" => array ("google" => "Fondamento", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Fontdiner Swanky" => array ("google" => "Fontdiner+Swanky", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Forum" => array ("google" => "Forum", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Francois One" => array ("google" => "Francois+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Freckle Face" => array ("google" => "Freckle+Face", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fredericka the Great" => array ("google" => "Fredericka+the+Great", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fredoka One" => array ("google" => "Fredoka+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Freehand" => array ("google" => "Freehand", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fresca" => array ("google" => "Fresca", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Frijole" => array ("google" => "Frijole", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fruktur" => array ("google" => "Fruktur", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Fugaz One" => array ("google" => "Fugaz+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "GFS Didot" => array ("google" => "GFS+Didot", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "GFS Neohellenic" => array ("google" => "GFS+Neohellenic", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Gabriela" => array ("google" => "Gabriela", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gafata" => array ("google" => "Gafata", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Galdeano" => array ("google" => "Galdeano", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Galindo" => array ("google" => "Galindo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gentium Basic" => array ("google" => "Gentium+Basic", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Gentium Book Basic" => array ("google" => "Gentium+Book+Basic", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Geo" => array ("google" => "Geo", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Geostar" => array ("google" => "Geostar", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Geostar Fill" => array ("google" => "Geostar+Fill", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Germania One" => array ("google" => "Germania+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gidugu" => array ("google" => "Gidugu", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gilda Display" => array ("google" => "Gilda+Display", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Give You Glory" => array ("google" => "Give+You+Glory", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Glass Antiqua" => array ("google" => "Glass+Antiqua", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Glegoo" => array ("google" => "Glegoo", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Gloria Hallelujah" => array ("google" => "Gloria+Hallelujah", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Goblin One" => array ("google" => "Goblin+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gochi Hand" => array ("google" => "Gochi+Hand", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gorditas" => array ("google" => "Gorditas", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Goudy Bookletter 1911" => array ("google" => "Goudy+Bookletter+1911", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Graduate" => array ("google" => "Graduate", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Grand Hotel" => array ("google" => "Grand+Hotel", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gravitas One" => array ("google" => "Gravitas+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Great Vibes" => array ("google" => "Great+Vibes", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Griffy" => array ("google" => "Griffy", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gruppo" => array ("google" => "Gruppo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Gudea" => array ("google" => "Gudea", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Gurajada" => array ("google" => "Gurajada", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Habibi" => array ("google" => "Habibi", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Halant" => array ("google" => "Halant", "variants" => "300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Hammersmith One" => array ("google" => "Hammersmith+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Hanalei" => array ("google" => "Hanalei", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Hanalei Fill" => array ("google" => "Hanalei+Fill", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Handlee" => array ("google" => "Handlee", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Hanuman" => array ("google" => "Hanuman", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Happy Monkey" => array ("google" => "Happy+Monkey", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Headland One" => array ("google" => "Headland+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Henny Penny" => array ("google" => "Henny+Penny", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Herr Von Muellerhoff" => array ("google" => "Herr+Von+Muellerhoff", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Hind" => array ("google" => "Hind", "variants" => "300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Holtwood One SC" => array ("google" => "Holtwood+One+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Homemade Apple" => array ("google" => "Homemade+Apple", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Homenaje" => array ("google" => "Homenaje", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "IM Fell DW Pica" => array ("google" => "IM+Fell+DW+Pica", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "IM Fell DW Pica SC" => array ("google" => "IM+Fell+DW+Pica+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "IM Fell Double Pica" => array ("google" => "IM+Fell+Double+Pica", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "IM Fell Double Pica SC" => array ("google" => "IM+Fell+Double+Pica+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "IM Fell English" => array ("google" => "IM+Fell+English", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "IM Fell English SC" => array ("google" => "IM+Fell+English+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "IM Fell French Canon" => array ("google" => "IM+Fell+French+Canon", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "IM Fell French Canon SC" => array ("google" => "IM+Fell+French+Canon+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "IM Fell Great Primer" => array ("google" => "IM+Fell+Great+Primer", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "IM Fell Great Primer SC" => array ("google" => "IM+Fell+Great+Primer+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Iceberg" => array ("google" => "Iceberg", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Iceland" => array ("google" => "Iceland", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Imprima" => array ("google" => "Imprima", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Inconsolata" => array ("google" => "Inconsolata", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Inder" => array ("google" => "Inder", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Indie Flower" => array ("google" => "Indie+Flower", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Inika" => array ("google" => "Inika", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Irish Grover" => array ("google" => "Irish+Grover", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Istok Web" => array ("google" => "Istok+Web", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Italiana" => array ("google" => "Italiana", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Italianno" => array ("google" => "Italianno", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Jacques Francois" => array ("google" => "Jacques+Francois", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Jacques Francois Shadow" => array ("google" => "Jacques+Francois+Shadow", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Jaldi" => array ("google" => "Jaldi", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Jim Nightshade" => array ("google" => "Jim+Nightshade", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Jockey One" => array ("google" => "Jockey+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Jolly Lodger" => array ("google" => "Jolly+Lodger", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Josefin Sans" => array ("google" => "Josefin+Sans", "variants" => "100,100italic,300,300italic,regular,italic,600,600italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Josefin Slab" => array ("google" => "Josefin+Slab", "variants" => "100,100italic,300,300italic,regular,italic,600,600italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Joti One" => array ("google" => "Joti+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Judson" => array ("google" => "Judson", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Julee" => array ("google" => "Julee", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Julius Sans One" => array ("google" => "Julius+Sans+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Junge" => array ("google" => "Junge", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Jura" => array ("google" => "Jura", "variants" => "300,regular,500,600", "active" => "false", "favorite" => "false"),
        "Just Another Hand" => array ("google" => "Just+Another+Hand", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Just Me Again Down Here" => array ("google" => "Just+Me+Again+Down+Here", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kalam" => array ("google" => "Kalam", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Kameron" => array ("google" => "Kameron", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Kantumruy" => array ("google" => "Kantumruy", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Karla" => array ("google" => "Karla", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Karma" => array ("google" => "Karma", "variants" => "300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Kaushan Script" => array ("google" => "Kaushan+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kavoon" => array ("google" => "Kavoon", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kdam Thmor" => array ("google" => "Kdam+Thmor", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Keania One" => array ("google" => "Keania+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kelly Slab" => array ("google" => "Kelly+Slab", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kenia" => array ("google" => "Kenia", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Khand" => array ("google" => "Khand", "variants" => "300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Khmer" => array ("google" => "Khmer", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Khula" => array ("google" => "Khula", "variants" => "300,regular,600,700,800", "active" => "false", "favorite" => "false"),
        "Kite One" => array ("google" => "Kite+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Knewave" => array ("google" => "Knewave", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kotta One" => array ("google" => "Kotta+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Koulen" => array ("google" => "Koulen", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kranky" => array ("google" => "Kranky", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Kreon" => array ("google" => "Kreon", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Kristi" => array ("google" => "Kristi", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Krona One" => array ("google" => "Krona+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "La Belle Aurore" => array ("google" => "La+Belle+Aurore", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Laila" => array ("google" => "Laila", "variants" => "300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Lakki Reddy" => array ("google" => "Lakki+Reddy", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lancelot" => array ("google" => "Lancelot", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lateef" => array ("google" => "Lateef", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lato" => array ("google" => "Lato", "variants" => "100,100italic,300,300italic,regular,italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "League Script" => array ("google" => "League+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Leckerli One" => array ("google" => "Leckerli+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ledger" => array ("google" => "Ledger", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lekton" => array ("google" => "Lekton", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Lemon" => array ("google" => "Lemon", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Libre Baskerville" => array ("google" => "Libre+Baskerville", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Life Savers" => array ("google" => "Life+Savers", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Lilita One" => array ("google" => "Lilita+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lily Script One" => array ("google" => "Lily+Script+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Limelight" => array ("google" => "Limelight", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Linden Hill" => array ("google" => "Linden+Hill", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Lobster" => array ("google" => "Lobster", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lobster Two" => array ("google" => "Lobster+Two", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Londrina Outline" => array ("google" => "Londrina+Outline", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Londrina Shadow" => array ("google" => "Londrina+Shadow", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Londrina Sketch" => array ("google" => "Londrina+Sketch", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Londrina Solid" => array ("google" => "Londrina+Solid", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lora" => array ("google" => "Lora", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Love Ya Like A Sister" => array ("google" => "Love+Ya+Like+A+Sister", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Loved by the King" => array ("google" => "Loved+by+the+King", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lovers Quarrel" => array ("google" => "Lovers+Quarrel", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Luckiest Guy" => array ("google" => "Luckiest+Guy", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Lusitana" => array ("google" => "Lusitana", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Lustria" => array ("google" => "Lustria", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Macondo" => array ("google" => "Macondo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Macondo Swash Caps" => array ("google" => "Macondo+Swash+Caps", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Magra" => array ("google" => "Magra", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Maiden Orange" => array ("google" => "Maiden+Orange", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mako" => array ("google" => "Mako", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mallanna" => array ("google" => "Mallanna", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mandali" => array ("google" => "Mandali", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Marcellus" => array ("google" => "Marcellus", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Marcellus SC" => array ("google" => "Marcellus+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Marck Script" => array ("google" => "Marck+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Margarine" => array ("google" => "Margarine", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Marko One" => array ("google" => "Marko+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Marmelad" => array ("google" => "Marmelad", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Martel" => array ("google" => "Martel", "variants" => "200,300,regular,600,700,800,900", "active" => "false", "favorite" => "false"),
        "Martel Sans" => array ("google" => "Martel+Sans", "variants" => "200,300,regular,600,700,800,900", "active" => "false", "favorite" => "false"),
        "Marvel" => array ("google" => "Marvel", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Mate" => array ("google" => "Mate", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Mate SC" => array ("google" => "Mate+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Maven Pro" => array ("google" => "Maven+Pro", "variants" => "regular,500,700,900", "active" => "false", "favorite" => "false"),
        "McLaren" => array ("google" => "McLaren", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Meddon" => array ("google" => "Meddon", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "MedievalSharp" => array ("google" => "MedievalSharp", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Medula One" => array ("google" => "Medula+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Megrim" => array ("google" => "Megrim", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Meie Script" => array ("google" => "Meie+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Merienda" => array ("google" => "Merienda", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Merienda One" => array ("google" => "Merienda+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Merriweather" => array ("google" => "Merriweather", "variants" => "300,300italic,regular,italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Merriweather Sans" => array ("google" => "Merriweather+Sans", "variants" => "300,300italic,regular,italic,700,700italic,800,800italic", "active" => "false", "favorite" => "false"),
        "Metal" => array ("google" => "Metal", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Metal Mania" => array ("google" => "Metal+Mania", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Metamorphous" => array ("google" => "Metamorphous", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Metrophobic" => array ("google" => "Metrophobic", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Michroma" => array ("google" => "Michroma", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Milonga" => array ("google" => "Milonga", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Miltonian" => array ("google" => "Miltonian", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Miltonian Tattoo" => array ("google" => "Miltonian+Tattoo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Miniver" => array ("google" => "Miniver", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Miss Fajardose" => array ("google" => "Miss+Fajardose", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Modak" => array ("google" => "Modak", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Modern Antiqua" => array ("google" => "Modern+Antiqua", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Molengo" => array ("google" => "Molengo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Molle" => array ("google" => "Molle", "variants" => "italic", "active" => "false", "favorite" => "false"),
        "Monda" => array ("google" => "Monda", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Monofett" => array ("google" => "Monofett", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Monoton" => array ("google" => "Monoton", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Monsieur La Doulaise" => array ("google" => "Monsieur+La+Doulaise", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Montaga" => array ("google" => "Montaga", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Montez" => array ("google" => "Montez", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Montserrat" => array ("google" => "Montserrat", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Montserrat Alternates" => array ("google" => "Montserrat+Alternates", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Montserrat Subrayada" => array ("google" => "Montserrat+Subrayada", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Moul" => array ("google" => "Moul", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Moulpali" => array ("google" => "Moulpali", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mountains of Christmas" => array ("google" => "Mountains+of+Christmas", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Mouse Memoirs" => array ("google" => "Mouse+Memoirs", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mr Bedfort" => array ("google" => "Mr+Bedfort", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mr Dafoe" => array ("google" => "Mr+Dafoe", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mr De Haviland" => array ("google" => "Mr+De+Haviland", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mrs Saint Delafield" => array ("google" => "Mrs+Saint+Delafield", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Mrs Sheppards" => array ("google" => "Mrs+Sheppards", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Muli" => array ("google" => "Muli", "variants" => "300,300italic,regular,italic", "active" => "false", "favorite" => "false"),
        "Mystery Quest" => array ("google" => "Mystery+Quest", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "NTR" => array ("google" => "NTR", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Neucha" => array ("google" => "Neucha", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Neuton" => array ("google" => "Neuton", "variants" => "200,300,regular,italic,700,800", "active" => "false", "favorite" => "false"),
        "New Rocker" => array ("google" => "New+Rocker", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "News Cycle" => array ("google" => "News+Cycle", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Niconne" => array ("google" => "Niconne", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nixie One" => array ("google" => "Nixie+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nobile" => array ("google" => "Nobile", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Nokora" => array ("google" => "Nokora", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Norican" => array ("google" => "Norican", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nosifer" => array ("google" => "Nosifer", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nothing You Could Do" => array ("google" => "Nothing+You+Could+Do", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Noticia Text" => array ("google" => "Noticia+Text", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Noto Sans" => array ("google" => "Noto+Sans", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Noto Serif" => array ("google" => "Noto+Serif", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Nova Cut" => array ("google" => "Nova+Cut", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nova Flat" => array ("google" => "Nova+Flat", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nova Mono" => array ("google" => "Nova+Mono", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nova Oval" => array ("google" => "Nova+Oval", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nova Round" => array ("google" => "Nova+Round", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nova Script" => array ("google" => "Nova+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nova Slim" => array ("google" => "Nova+Slim", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nova Square" => array ("google" => "Nova+Square", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Numans" => array ("google" => "Numans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Nunito" => array ("google" => "Nunito", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Odor Mean Chey" => array ("google" => "Odor+Mean+Chey", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Offside" => array ("google" => "Offside", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Old Standard TT" => array ("google" => "Old+Standard+TT", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Oldenburg" => array ("google" => "Oldenburg", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Oleo Script" => array ("google" => "Oleo+Script", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Oleo Script Swash Caps" => array ("google" => "Oleo+Script+Swash+Caps", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Open Sans" => array ("google" => "Open+Sans", "variants" => "300,300italic,regular,italic,600,600italic,700,700italic,800,800italic", "active" => "false", "favorite" => "false"),
        "Open Sans Condensed" => array ("google" => "Open+Sans+Condensed", "variants" => "300,300italic,700", "active" => "false", "favorite" => "false"),
        "Oranienbaum" => array ("google" => "Oranienbaum", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Orbitron" => array ("google" => "Orbitron", "variants" => "regular,500,700,900", "active" => "false", "favorite" => "false"),
        "Oregano" => array ("google" => "Oregano", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Orienta" => array ("google" => "Orienta", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Original Surfer" => array ("google" => "Original+Surfer", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Oswald" => array ("google" => "Oswald", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Over the Rainbow" => array ("google" => "Over+the+Rainbow", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Overlock" => array ("google" => "Overlock", "variants" => "regular,italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Overlock SC" => array ("google" => "Overlock+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ovo" => array ("google" => "Ovo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Oxygen" => array ("google" => "Oxygen", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Oxygen Mono" => array ("google" => "Oxygen+Mono", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "PT Mono" => array ("google" => "PT+Mono", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "PT Sans" => array ("google" => "PT+Sans", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "PT Sans Caption" => array ("google" => "PT+Sans+Caption", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "PT Sans Narrow" => array ("google" => "PT+Sans+Narrow", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "PT Serif" => array ("google" => "PT+Serif", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "PT Serif Caption" => array ("google" => "PT+Serif+Caption", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Pacifico" => array ("google" => "Pacifico", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Palanquin" => array ("google" => "Palanquin", "variants" => "100,200,300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Palanquin Dark" => array ("google" => "Palanquin+Dark", "variants" => "regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Paprika" => array ("google" => "Paprika", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Parisienne" => array ("google" => "Parisienne", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Passero One" => array ("google" => "Passero+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Passion One" => array ("google" => "Passion+One", "variants" => "regular,700,900", "active" => "false", "favorite" => "false"),
        "Pathway Gothic One" => array ("google" => "Pathway+Gothic+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Patrick Hand" => array ("google" => "Patrick+Hand", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Patrick Hand SC" => array ("google" => "Patrick+Hand+SC", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Patua One" => array ("google" => "Patua+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Paytone One" => array ("google" => "Paytone+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Peddana" => array ("google" => "Peddana", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Peralta" => array ("google" => "Peralta", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Permanent Marker" => array ("google" => "Permanent+Marker", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Petit Formal Script" => array ("google" => "Petit+Formal+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Petrona" => array ("google" => "Petrona", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Philosopher" => array ("google" => "Philosopher", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Piedra" => array ("google" => "Piedra", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Pinyon Script" => array ("google" => "Pinyon+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Pirata One" => array ("google" => "Pirata+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Plaster" => array ("google" => "Plaster", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Play" => array ("google" => "Play", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Playball" => array ("google" => "Playball", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Playfair Display" => array ("google" => "Playfair+Display", "variants" => "regular,italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Playfair Display SC" => array ("google" => "Playfair+Display+SC", "variants" => "regular,italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Podkova" => array ("google" => "Podkova", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Poiret One" => array ("google" => "Poiret+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Poller One" => array ("google" => "Poller+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Poly" => array ("google" => "Poly", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Pompiere" => array ("google" => "Pompiere", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Pontano Sans" => array ("google" => "Pontano+Sans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Port Lligat Sans" => array ("google" => "Port+Lligat+Sans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Port Lligat Slab" => array ("google" => "Port+Lligat+Slab", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Pragati Narrow" => array ("google" => "Pragati+Narrow", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Prata" => array ("google" => "Prata", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Preahvihear" => array ("google" => "Preahvihear", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Press Start 2P" => array ("google" => "Press+Start+2P", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Princess Sofia" => array ("google" => "Princess+Sofia", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Prociono" => array ("google" => "Prociono", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Prosto One" => array ("google" => "Prosto+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Puritan" => array ("google" => "Puritan", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Purple Purse" => array ("google" => "Purple+Purse", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Quando" => array ("google" => "Quando", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Quantico" => array ("google" => "Quantico", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Quattrocento" => array ("google" => "Quattrocento", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Quattrocento Sans" => array ("google" => "Quattrocento+Sans", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Questrial" => array ("google" => "Questrial", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Quicksand" => array ("google" => "Quicksand", "variants" => "300,regular,700", "active" => "false", "favorite" => "false"),
        "Quintessential" => array ("google" => "Quintessential", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Qwigley" => array ("google" => "Qwigley", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Racing Sans One" => array ("google" => "Racing+Sans+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Radley" => array ("google" => "Radley", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Rajdhani" => array ("google" => "Rajdhani", "variants" => "300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Raleway" => array ("google" => "Raleway", "variants" => "100,200,300,regular,500,600,700,800,900", "active" => "false", "favorite" => "false"),
        "Raleway Dots" => array ("google" => "Raleway+Dots", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ramabhadra" => array ("google" => "Ramabhadra", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ramaraja" => array ("google" => "Ramaraja", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rambla" => array ("google" => "Rambla", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Rammetto One" => array ("google" => "Rammetto+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ranchers" => array ("google" => "Ranchers", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rancho" => array ("google" => "Rancho", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ranga" => array ("google" => "Ranga", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Rationale" => array ("google" => "Rationale", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ravi Prakash" => array ("google" => "Ravi+Prakash", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Redressed" => array ("google" => "Redressed", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Reenie Beanie" => array ("google" => "Reenie+Beanie", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Revalia" => array ("google" => "Revalia", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ribeye" => array ("google" => "Ribeye", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ribeye Marrow" => array ("google" => "Ribeye+Marrow", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Righteous" => array ("google" => "Righteous", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Risque" => array ("google" => "Risque", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Roboto" => array ("google" => "Roboto", "variants" => "100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Roboto Condensed" => array ("google" => "Roboto+Condensed", "variants" => "300,300italic,regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Roboto Slab" => array ("google" => "Roboto+Slab", "variants" => "100,300,regular,700", "active" => "false", "favorite" => "false"),
        "Rochester" => array ("google" => "Rochester", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rock Salt" => array ("google" => "Rock+Salt", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rokkitt" => array ("google" => "Rokkitt", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Romanesco" => array ("google" => "Romanesco", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ropa Sans" => array ("google" => "Ropa+Sans", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Rosario" => array ("google" => "Rosario", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Rosarivo" => array ("google" => "Rosarivo", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Rouge Script" => array ("google" => "Rouge+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rozha One" => array ("google" => "Rozha+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rubik Mono One" => array ("google" => "Rubik+Mono+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rubik One" => array ("google" => "Rubik+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ruda" => array ("google" => "Ruda", "variants" => "regular,700,900", "active" => "false", "favorite" => "false"),
        "Rufina" => array ("google" => "Rufina", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Ruge Boogie" => array ("google" => "Ruge+Boogie", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ruluko" => array ("google" => "Ruluko", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rum Raisin" => array ("google" => "Rum+Raisin", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ruslan Display" => array ("google" => "Ruslan+Display", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Russo One" => array ("google" => "Russo+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ruthie" => array ("google" => "Ruthie", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Rye" => array ("google" => "Rye", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sacramento" => array ("google" => "Sacramento", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sail" => array ("google" => "Sail", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Salsa" => array ("google" => "Salsa", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sanchez" => array ("google" => "Sanchez", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Sancreek" => array ("google" => "Sancreek", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sansita One" => array ("google" => "Sansita+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sarina" => array ("google" => "Sarina", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sarpanch" => array ("google" => "Sarpanch", "variants" => "regular,500,600,700,800,900", "active" => "false", "favorite" => "false"),
        "Satisfy" => array ("google" => "Satisfy", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Scada" => array ("google" => "Scada", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Scheherazade" => array ("google" => "Scheherazade", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Schoolbell" => array ("google" => "Schoolbell", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Seaweed Script" => array ("google" => "Seaweed+Script", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sevillana" => array ("google" => "Sevillana", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Seymour One" => array ("google" => "Seymour+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Shadows Into Light" => array ("google" => "Shadows+Into+Light", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Shadows Into Light Two" => array ("google" => "Shadows+Into+Light+Two", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Shanti" => array ("google" => "Shanti", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Share" => array ("google" => "Share", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Share Tech" => array ("google" => "Share+Tech", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Share Tech Mono" => array ("google" => "Share+Tech+Mono", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Shojumaru" => array ("google" => "Shojumaru", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Short Stack" => array ("google" => "Short+Stack", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Siemreap" => array ("google" => "Siemreap", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sigmar One" => array ("google" => "Sigmar+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Signika" => array ("google" => "Signika", "variants" => "300,regular,600,700", "active" => "false", "favorite" => "false"),
        "Signika Negative" => array ("google" => "Signika+Negative", "variants" => "300,regular,600,700", "active" => "false", "favorite" => "false"),
        "Simonetta" => array ("google" => "Simonetta", "variants" => "regular,italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Sintony" => array ("google" => "Sintony", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Sirin Stencil" => array ("google" => "Sirin+Stencil", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Six Caps" => array ("google" => "Six+Caps", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Skranji" => array ("google" => "Skranji", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Slabo 13px" => array ("google" => "Slabo+13px", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Slabo 27px" => array ("google" => "Slabo+27px", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Slackey" => array ("google" => "Slackey", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Smokum" => array ("google" => "Smokum", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Smythe" => array ("google" => "Smythe", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sniglet" => array ("google" => "Sniglet", "variants" => "regular,800", "active" => "false", "favorite" => "false"),
        "Snippet" => array ("google" => "Snippet", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Snowburst One" => array ("google" => "Snowburst+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sofadi One" => array ("google" => "Sofadi+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sofia" => array ("google" => "Sofia", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sonsie One" => array ("google" => "Sonsie+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sorts Mill Goudy" => array ("google" => "Sorts+Mill+Goudy", "variants" => "regular,italic", "active" => "false", "favorite" => "false"),
        "Source Code Pro" => array ("google" => "Source+Code+Pro", "variants" => "200,300,regular,500,600,700,900", "active" => "false", "favorite" => "false"),
        "Source Sans Pro" => array ("google" => "Source+Sans+Pro", "variants" => "200,200italic,300,300italic,regular,italic,600,600italic,700,700italic,900,900italic", "active" => "false", "favorite" => "false"),
        "Source Serif Pro" => array ("google" => "Source+Serif+Pro", "variants" => "regular,600,700", "active" => "false", "favorite" => "false"),
        "Special Elite" => array ("google" => "Special+Elite", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Spicy Rice" => array ("google" => "Spicy+Rice", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Spinnaker" => array ("google" => "Spinnaker", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Spirax" => array ("google" => "Spirax", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Squada One" => array ("google" => "Squada+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sree Krushnadevaraya" => array ("google" => "Sree+Krushnadevaraya", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Stalemate" => array ("google" => "Stalemate", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Stalinist One" => array ("google" => "Stalinist+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Stardos Stencil" => array ("google" => "Stardos+Stencil", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Stint Ultra Condensed" => array ("google" => "Stint+Ultra+Condensed", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Stint Ultra Expanded" => array ("google" => "Stint+Ultra+Expanded", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Stoke" => array ("google" => "Stoke", "variants" => "300,regular", "active" => "false", "favorite" => "false"),
        "Strait" => array ("google" => "Strait", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sue Ellen Francisco" => array ("google" => "Sue+Ellen+Francisco", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Sunshiney" => array ("google" => "Sunshiney", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Supermercado One" => array ("google" => "Supermercado+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Suranna" => array ("google" => "Suranna", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Suravaram" => array ("google" => "Suravaram", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Suwannaphum" => array ("google" => "Suwannaphum", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Swanky and Moo Moo" => array ("google" => "Swanky+and+Moo+Moo", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Syncopate" => array ("google" => "Syncopate", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Tangerine" => array ("google" => "Tangerine", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Taprom" => array ("google" => "Taprom", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Tauri" => array ("google" => "Tauri", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Teko" => array ("google" => "Teko", "variants" => "300,regular,500,600,700", "active" => "false", "favorite" => "false"),
        "Telex" => array ("google" => "Telex", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Tenali Ramakrishna" => array ("google" => "Tenali+Ramakrishna", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Tenor Sans" => array ("google" => "Tenor+Sans", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Text Me One" => array ("google" => "Text+Me+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "The Girl Next Door" => array ("google" => "The+Girl+Next+Door", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Tienne" => array ("google" => "Tienne", "variants" => "regular,700,900", "active" => "false", "favorite" => "false"),
        "Timmana" => array ("google" => "Timmana", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Tinos" => array ("google" => "Tinos", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Titan One" => array ("google" => "Titan+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Titillium Web" => array ("google" => "Titillium+Web", "variants" => "200,200italic,300,300italic,regular,italic,600,600italic,700,700italic,900", "active" => "false", "favorite" => "false"),
        "Trade Winds" => array ("google" => "Trade+Winds", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Trocchi" => array ("google" => "Trocchi", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Trochut" => array ("google" => "Trochut", "variants" => "regular,italic,700", "active" => "false", "favorite" => "false"),
        "Trykker" => array ("google" => "Trykker", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Tulpen One" => array ("google" => "Tulpen+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ubuntu" => array ("google" => "Ubuntu", "variants" => "300,300italic,regular,italic,500,500italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Ubuntu Condensed" => array ("google" => "Ubuntu+Condensed", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Ubuntu Mono" => array ("google" => "Ubuntu+Mono", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Ultra" => array ("google" => "Ultra", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Uncial Antiqua" => array ("google" => "Uncial+Antiqua", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Underdog" => array ("google" => "Underdog", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Unica One" => array ("google" => "Unica+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "UnifrakturCook" => array ("google" => "UnifrakturCook", "variants" => "700", "active" => "false", "favorite" => "false"),
        "UnifrakturMaguntia" => array ("google" => "UnifrakturMaguntia", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Unkempt" => array ("google" => "Unkempt", "variants" => "regular,700", "active" => "false", "favorite" => "false"),
        "Unlock" => array ("google" => "Unlock", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Unna" => array ("google" => "Unna", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "VT323" => array ("google" => "VT323", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Vampiro One" => array ("google" => "Vampiro+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Varela" => array ("google" => "Varela", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Varela Round" => array ("google" => "Varela+Round", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Vast Shadow" => array ("google" => "Vast+Shadow", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Vesper Libre" => array ("google" => "Vesper+Libre", "variants" => "regular,500,700,900", "active" => "false", "favorite" => "false"),
        "Vibur" => array ("google" => "Vibur", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Vidaloka" => array ("google" => "Vidaloka", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Viga" => array ("google" => "Viga", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Voces" => array ("google" => "Voces", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Volkhov" => array ("google" => "Volkhov", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Vollkorn" => array ("google" => "Vollkorn", "variants" => "regular,italic,700,700italic", "active" => "false", "favorite" => "false"),
        "Voltaire" => array ("google" => "Voltaire", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Waiting for the Sunrise" => array ("google" => "Waiting+for+the+Sunrise", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Wallpoet" => array ("google" => "Wallpoet", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Walter Turncoat" => array ("google" => "Walter+Turncoat", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Warnes" => array ("google" => "Warnes", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Wellfleet" => array ("google" => "Wellfleet", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Wendy One" => array ("google" => "Wendy+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Wire One" => array ("google" => "Wire+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Yanone Kaffeesatz" => array ("google" => "Yanone+Kaffeesatz", "variants" => "200,300,regular,700", "active" => "false", "favorite" => "false"),
        "Yellowtail" => array ("google" => "Yellowtail", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Yeseva One" => array ("google" => "Yeseva+One", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Yesteryear" => array ("google" => "Yesteryear", "variants" => "regular", "active" => "false", "favorite" => "false"),
        "Zeyada" => array ("google" => "Zeyada", "variants" => "regular", "active" => "false", "favorite" => "false"),
    );
?>